<?php
/**
 * BlankDesignSourceSettingsModel
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;

use \ArrayAccess;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * BlankDesignSourceSettingsModel Class Doc Comment
 *
 * @category Class
 * @description Parameters of an existing design that should become a template for a new blank design.
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BlankDesignSourceSettingsModel implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BlankDesignSourceSettingsModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'design_id' => 'string',
        'design_surface_index' => 'int',
        'preserve_print_areas' => 'bool',
        'preserve_surface_items' => 'bool',
        'match_surfaces' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'design_id' => null,
        'design_surface_index' => 'int32',
        'preserve_print_areas' => null,
        'preserve_surface_items' => null,
        'match_surfaces' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'design_id' => true,
        'design_surface_index' => true,
        'preserve_print_areas' => false,
        'preserve_surface_items' => false,
        'match_surfaces' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'design_id' => 'designId',
        'design_surface_index' => 'designSurfaceIndex',
        'preserve_print_areas' => 'preservePrintAreas',
        'preserve_surface_items' => 'preserveSurfaceItems',
        'match_surfaces' => 'matchSurfaces'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'design_id' => 'setDesignId',
        'design_surface_index' => 'setDesignSurfaceIndex',
        'preserve_print_areas' => 'setPreservePrintAreas',
        'preserve_surface_items' => 'setPreserveSurfaceItems',
        'match_surfaces' => 'setMatchSurfaces'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'design_id' => 'getDesignId',
        'design_surface_index' => 'getDesignSurfaceIndex',
        'preserve_print_areas' => 'getPreservePrintAreas',
        'preserve_surface_items' => 'getPreserveSurfaceItems',
        'match_surfaces' => 'getMatchSurfaces'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('design_id', $data ?? [], null);
        $this->setIfExists('design_surface_index', $data ?? [], null);
        $this->setIfExists('preserve_print_areas', $data ?? [], null);
        $this->setIfExists('preserve_surface_items', $data ?? [], null);
        $this->setIfExists('match_surfaces', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets design_id
     *
     * @return string|null
     */
    public function getDesignId()
    {
        return $this->container['design_id'];
    }

    /**
     * Sets design_id
     *
     * @param string|null $design_id Source design identifier.
     *
     * @return self
     */
    public function setDesignId($design_id)
    {
        if (is_null($design_id)) {
            array_push($this->openAPINullablesSetToNull, 'design_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('design_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['design_id'] = $design_id;

        return $this;
    }

    /**
     * Gets design_surface_index
     *
     * @return int|null
     */
    public function getDesignSurfaceIndex()
    {
        return $this->container['design_surface_index'];
    }

    /**
     * Sets design_surface_index
     *
     * @param int|null $design_surface_index Index (zero-based) of a surface in a source design that should be used as a template for a new blank design.  If not set, first surface of the source design will be used.
     *
     * @return self
     */
    public function setDesignSurfaceIndex($design_surface_index)
    {
        if (is_null($design_surface_index)) {
            array_push($this->openAPINullablesSetToNull, 'design_surface_index');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('design_surface_index', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['design_surface_index'] = $design_surface_index;

        return $this;
    }

    /**
     * Gets preserve_print_areas
     *
     * @return bool|null
     */
    public function getPreservePrintAreas()
    {
        return $this->container['preserve_print_areas'];
    }

    /**
     * Sets preserve_print_areas
     *
     * @param bool|null $preserve_print_areas Flag that indicates whether original surface print areas should be used.  If value is `false`, a new print area will be created with size and margins specified in Aurigma.AssetProcessor.WebApi.Models.Design.BlankDesignSettingsModel.
     *
     * @return self
     */
    public function setPreservePrintAreas($preserve_print_areas)
    {
        if (is_null($preserve_print_areas)) {
            throw new \InvalidArgumentException('non-nullable preserve_print_areas cannot be null');
        }
        $this->container['preserve_print_areas'] = $preserve_print_areas;

        return $this;
    }

    /**
     * Gets preserve_surface_items
     *
     * @return bool|null
     */
    public function getPreserveSurfaceItems()
    {
        return $this->container['preserve_surface_items'];
    }

    /**
     * Sets preserve_surface_items
     *
     * @param bool|null $preserve_surface_items Flag that indicates whether original surface items should be preserved.  If value is `false`, target design surfaces will be blank.
     *
     * @return self
     */
    public function setPreserveSurfaceItems($preserve_surface_items)
    {
        if (is_null($preserve_surface_items)) {
            throw new \InvalidArgumentException('non-nullable preserve_surface_items cannot be null');
        }
        $this->container['preserve_surface_items'] = $preserve_surface_items;

        return $this;
    }

    /**
     * Gets match_surfaces
     *
     * @return bool|null
     */
    public function getMatchSurfaces()
    {
        return $this->container['match_surfaces'];
    }

    /**
     * Sets match_surfaces
     *
     * @param bool|null $match_surfaces Flag that indicates whether original design surfaces should be places in new design in original order.  If value is `true`, `DesignSurfaceIndex` parameter will be ignored.  If target blank design has more surfaces than the original one, last original surface will be repeated to the end.
     *
     * @return self
     */
    public function setMatchSurfaces($match_surfaces)
    {
        if (is_null($match_surfaces)) {
            throw new \InvalidArgumentException('non-nullable match_surfaces cannot be null');
        }
        $this->container['match_surfaces'] = $match_surfaces;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


