<?php
/**
 * ColorProfileClass
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * ColorProfileClass Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ColorProfileClass
{
    /**
     * Possible values of this enum
     */
    const UNKNOWN = 'Unknown';
    const _ABSTRACT = 'Abstract';
    const LINK = 'Link';
    const DISPLAY = 'Display';
    const NAMED_COLOR = 'NamedColor';
    const OUTPUT = 'Output';
    const INPUT = 'Input';
    const COLOR_SPACE = 'ColorSpace';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::_ABSTRACT,
            self::LINK,
            self::DISPLAY,
            self::NAMED_COLOR,
            self::OUTPUT,
            self::INPUT,
            self::COLOR_SPACE,
        ];
    }
}


