<?php
/**
 * DataSchemaValidationRule
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * DataSchemaValidationRule Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DataSchemaValidationRule
{
    /**
     * Possible values of this enum
     */
    const OK = 'Ok';
    const MISSING = 'Missing';
    const REQUIRED = 'Required';
    const NO_SUCH_FIELD = 'NoSuchField';
    const STRING_PATTERN = 'StringPattern';
    const STRING_MIN_LENGTH = 'StringMinLength';
    const STRING_MAX_LENGTH = 'StringMaxLength';
    const STRING_MIN_LENGTH_PER_LINE = 'StringMinLengthPerLine';
    const STRING_MAX_LENGTH_PER_LINE = 'StringMaxLengthPerLine';
    const STRING_MIN_LINES = 'StringMinLines';
    const STRING_MAX_LINES = 'StringMaxLines';
    const NUMBER_IS_NUMBER = 'NumberIsNumber';
    const NUMBER_MIN = 'NumberMin';
    const NUMBER_MAX = 'NumberMax';
    const NUMBER_IS_INTEGER = 'NumberIsInteger';
    const VARIANT_NOT_IN_LIST = 'VariantNotInList';
    const IMAGE_ROOT = 'ImageRoot';
    const IMAGE_NOT_FOUND = 'ImageNotFound';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::OK,
            self::MISSING,
            self::REQUIRED,
            self::NO_SUCH_FIELD,
            self::STRING_PATTERN,
            self::STRING_MIN_LENGTH,
            self::STRING_MAX_LENGTH,
            self::STRING_MIN_LENGTH_PER_LINE,
            self::STRING_MAX_LENGTH_PER_LINE,
            self::STRING_MIN_LINES,
            self::STRING_MAX_LINES,
            self::NUMBER_IS_NUMBER,
            self::NUMBER_MIN,
            self::NUMBER_MAX,
            self::NUMBER_IS_INTEGER,
            self::VARIANT_NOT_IN_LIST,
            self::IMAGE_ROOT,
            self::IMAGE_NOT_FOUND,
        ];
    }
}


