<?php
/**
 * DesignImportConflictDto
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;

use \ArrayAccess;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * DesignImportConflictDto Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class DesignImportConflictDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DesignImportConflictDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'missing_fonts_conflict' => '\Aurigma\AssetProcessor\Model\MissingFontsConflictDto',
        'missing_images_conflict' => '\Aurigma\AssetProcessor\Model\MissingImagesConflictDto',
        'name_conflict' => '\Aurigma\AssetProcessor\Model\NameConflictDto'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'missing_fonts_conflict' => null,
        'missing_images_conflict' => null,
        'name_conflict' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'missing_fonts_conflict' => 'missingFontsConflict',
        'missing_images_conflict' => 'missingImagesConflict',
        'name_conflict' => 'nameConflict'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'missing_fonts_conflict' => 'setMissingFontsConflict',
        'missing_images_conflict' => 'setMissingImagesConflict',
        'name_conflict' => 'setNameConflict'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'missing_fonts_conflict' => 'getMissingFontsConflict',
        'missing_images_conflict' => 'getMissingImagesConflict',
        'name_conflict' => 'getNameConflict'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['missing_fonts_conflict'] = $data['missing_fonts_conflict'] ?? null;
        $this->container['missing_images_conflict'] = $data['missing_images_conflict'] ?? null;
        $this->container['name_conflict'] = $data['name_conflict'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets missing_fonts_conflict
     *
     * @return \Aurigma\AssetProcessor\Model\MissingFontsConflictDto|null
     */
    public function getMissingFontsConflict()
    {
        return $this->container['missing_fonts_conflict'];
    }

    /**
     * Sets missing_fonts_conflict
     *
     * @param \Aurigma\AssetProcessor\Model\MissingFontsConflictDto|null $missing_fonts_conflict missing_fonts_conflict
     *
     * @return self
     */
    public function setMissingFontsConflict($missing_fonts_conflict)
    {
        $this->container['missing_fonts_conflict'] = $missing_fonts_conflict;

        return $this;
    }

    /**
     * Gets missing_images_conflict
     *
     * @return \Aurigma\AssetProcessor\Model\MissingImagesConflictDto|null
     */
    public function getMissingImagesConflict()
    {
        return $this->container['missing_images_conflict'];
    }

    /**
     * Sets missing_images_conflict
     *
     * @param \Aurigma\AssetProcessor\Model\MissingImagesConflictDto|null $missing_images_conflict missing_images_conflict
     *
     * @return self
     */
    public function setMissingImagesConflict($missing_images_conflict)
    {
        $this->container['missing_images_conflict'] = $missing_images_conflict;

        return $this;
    }

    /**
     * Gets name_conflict
     *
     * @return \Aurigma\AssetProcessor\Model\NameConflictDto|null
     */
    public function getNameConflict()
    {
        return $this->container['name_conflict'];
    }

    /**
     * Sets name_conflict
     *
     * @param \Aurigma\AssetProcessor\Model\NameConflictDto|null $name_conflict name_conflict
     *
     * @return self
     */
    public function setNameConflict($name_conflict)
    {
        $this->container['name_conflict'] = $name_conflict;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


