<?php
/**
 * MockupValidationProblemType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * MockupValidationProblemType Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MockupValidationProblemType
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const INVALID_FILE = 'InvalidFile';

    public const MISSING_SOURCE_FILE = 'MissingSourceFile';

    public const INVALID_SOURCE_FILE_FORMAT = 'InvalidSourceFileFormat';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::INVALID_FILE,
            self::MISSING_SOURCE_FILE,
            self::INVALID_SOURCE_FILE_FORMAT
        ];
    }
}


