<?php
/**
 * MockupLayerType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * MockupLayerType Class Doc Comment
 *
 * @category Class
 * @description Mockup layer type.
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MockupLayerType
{
    /**
     * Possible values of this enum
     */
    public const UNKNOWN = 'Unknown';

    public const IMAGE = 'Image';

    public const TEXT = 'Text';

    public const GROUP = 'Group';

    public const SHAPE = 'Shape';

    public const ARTWORK = 'Artwork';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UNKNOWN,
            self::IMAGE,
            self::TEXT,
            self::GROUP,
            self::SHAPE,
            self::ARTWORK
        ];
    }
}


