<?php
/**
 * MockupPreviewInterpolationMode
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Aurigma\AssetProcessor\Model;
use \Aurigma\AssetProcessor\ObjectSerializer;

/**
 * MockupPreviewInterpolationMode Class Doc Comment
 *
 * @category Class
 * @description Mockup preview interpolation mode.
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MockupPreviewInterpolationMode
{
    /**
     * Possible values of this enum
     */
    const HIGH = 'High';
    const MEDIUM = 'Medium';
    const LOW = 'Low';
    const NEAREST_NEIGHBOUR = 'NearestNeighbour';
    const LINEAR = 'Linear';
    const CUBIC = 'Cubic';
    const SUPERSAMPLING = 'Supersampling';
    const LANCZOS = 'Lanczos';
    const ANISOTROPIC4 = 'Anisotropic4';
    const ANISOTROPIC9 = 'Anisotropic9';
    const LANCZOS3 = 'Lanczos3';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::HIGH,
            self::MEDIUM,
            self::LOW,
            self::NEAREST_NEIGHBOUR,
            self::LINEAR,
            self::CUBIC,
            self::SUPERSAMPLING,
            self::LANCZOS,
            self::ANISOTROPIC4,
            self::ANISOTROPIC9,
            self::LANCZOS3,
        ];
    }
}


