<?php
/**
 * AurigmaAssetProcessorWebApiModelsDesignDesignCountPerSheetCalculationModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\AssetProcessor\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AurigmaAssetProcessorWebApiModelsDesignDesignCountPerSheetCalculationModelTest Class Doc Comment
 *
 * @category    Class
 * @description Model for calculating the design count per sheet of the specified size.
 * @package     Aurigma\AssetProcessor
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AurigmaAssetProcessorWebApiModelsDesignDesignCountPerSheetCalculationModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AurigmaAssetProcessorWebApiModelsDesignDesignCountPerSheetCalculationModel"
     */
    public function testAurigmaAssetProcessorWebApiModelsDesignDesignCountPerSheetCalculationModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheet_width"
     */
    public function testPropertySheetWidth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sheet_height"
     */
    public function testPropertySheetHeight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "print_area_index"
     */
    public function testPropertyPrintAreaIndex()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "margin"
     */
    public function testPropertyMargin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gap"
     */
    public function testPropertyGap()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
