<?php
/**
 * AurigmaAssetProcessorWebApiDtosDesignDesignPaletteValidationProblemDtoTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\AssetProcessor\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AurigmaAssetProcessorWebApiDtosDesignDesignPaletteValidationProblemDtoTest Class Doc Comment
 *
 * @category    Class
 * @description Palette validation problem description.
 * @package     Aurigma\AssetProcessor
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AurigmaAssetProcessorWebApiDtosDesignDesignPaletteValidationProblemDtoTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AurigmaAssetProcessorWebApiDtosDesignDesignPaletteValidationProblemDto"
     */
    public function testAurigmaAssetProcessorWebApiDtosDesignDesignPaletteValidationProblemDto()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "palette_id"
     */
    public function testPropertyPaletteId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "palette_uid"
     */
    public function testPropertyPaletteUid()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "relation"
     */
    public function testPropertyRelation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
