<?php
/**
 * CreateBlankDesignModelTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Aurigma\AssetProcessor\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreateBlankDesignModelTest Class Doc Comment
 *
 * @category    Class
 * @description &#39;Create blank design&#39; operation parameters.
 * @package     Aurigma\AssetProcessor
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreateBlankDesignModelTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreateBlankDesignModel"
     */
    public function testCreateBlankDesignModel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "design_params"
     */
    public function testPropertyDesignParams()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "preview_settings"
     */
    public function testPropertyPreviewSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blank_design_settings"
     */
    public function testPropertyBlankDesignSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "blank_design_source_settings"
     */
    public function testPropertyBlankDesignSourceSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
