<?php
/**
 * DesignProcessorApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetProcessor\Test\Api;

use \Aurigma\AssetProcessor\Configuration;
use \Aurigma\AssetProcessor\ApiException;
use \Aurigma\AssetProcessor\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DesignProcessorApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DesignProcessorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for designProcessorCalculateCountPerSheet
     *
     * Calculates the design count per sheet of the specified size..
     *
     */
    public function testDesignProcessorCalculateCountPerSheet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorCheck
     *
     * Checks if design taken from storage has any problems..
     *
     */
    public function testDesignProcessorCheck()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorCreateBlankDesign
     *
     * Creates design using basic settings and saves it to storage..
     *
     */
    public function testDesignProcessorCreateBlankDesign()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorCreateDesignFromMockup
     *
     * Creates design compatible to specified mockup and saves it to storage..
     *
     */
    public function testDesignProcessorCreateDesignFromMockup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorEmbedDataSchema
     *
     * Embeds linked data schema to the design file..
     *
     */
    public function testDesignProcessorEmbedDataSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorEmbedPalettes
     *
     * Embeds linked palettes to the design file..
     *
     */
    public function testDesignProcessorEmbedPalettes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorEmbedToggleSet
     *
     * Embeds linked toggle set to the design file..
     *
     */
    public function testDesignProcessorEmbedToggleSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorExportDesign
     *
     * Exports design file..
     *
     */
    public function testDesignProcessorExportDesign()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorExtractDataSchema
     *
     * Extracts data schema from design file and saves it to the specified folder..
     *
     */
    public function testDesignProcessorExtractDataSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorExtractPalettes
     *
     * Extracts palettes from design file and saves it to the specified folder.   Due to possibility of having linked and embedded palettes for same design, all linked palettes will be embedded before extraction..
     *
     */
    public function testDesignProcessorExtractPalettes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorExtractToggleSet
     *
     * Extracts toggle set from design file and saves it to the specified folder..
     *
     */
    public function testDesignProcessorExtractToggleSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorGetDepositPhotos
     *
     * Returns information about inserted images from DepositPhotos..
     *
     */
    public function testDesignProcessorGetDepositPhotos()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorImportDesign
     *
     * Imports design from source file and saves it to storage..
     *
     */
    public function testDesignProcessorImportDesign()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorLinkDataSchema
     *
     * Links data schema to the design file..
     *
     */
    public function testDesignProcessorLinkDataSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorLinkPalettes
     *
     * Links palettes to the design file..
     *
     */
    public function testDesignProcessorLinkPalettes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorLinkToggleSet
     *
     * Links toggle set to the design file..
     *
     */
    public function testDesignProcessorLinkToggleSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorPreparePreview
     *
     * Creates preview image for design taken from storage..
     *
     */
    public function testDesignProcessorPreparePreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorPreparePreviewUrl
     *
     * Creates preview image for design taken from storage..
     *
     */
    public function testDesignProcessorPreparePreviewUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorReimportDesign
     *
     * Re-imports design from source file and updates design file and metadata in storage..
     *
     */
    public function testDesignProcessorReimportDesign()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorRemoveDataSchema
     *
     * Removes data schema from the design file..
     *
     */
    public function testDesignProcessorRemoveDataSchema()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorRemovePalettes
     *
     * Removes palettes from the design file..
     *
     */
    public function testDesignProcessorRemovePalettes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorRemoveToggleSet
     *
     * Removes toggle set from the design file..
     *
     */
    public function testDesignProcessorRemoveToggleSet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorUpdate
     *
     * Updates design file and metadata in storage..
     *
     */
    public function testDesignProcessorUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for designProcessorValidateDesignImportSettings
     *
     * Validates the design import settings..
     *
     */
    public function testDesignProcessorValidateDesignImportSettings()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
