<?php
/**
 * FontProcessorApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetProcessor\Test\Api;

use \Aurigma\AssetProcessor\Configuration;
use \Aurigma\AssetProcessor\ApiException;
use \Aurigma\AssetProcessor\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FontProcessorApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FontProcessorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for fontProcessorImportFont
     *
     * Imports font from source file and saves it to storage..
     *
     */
    public function testFontProcessorImportFont()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontProcessorPreparePreview
     *
     * Creates preview image for font taken from storage..
     *
     */
    public function testFontProcessorPreparePreview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontProcessorPreparePreviewUrl
     *
     * Creates preview image for font taken from storage..
     *
     */
    public function testFontProcessorPreparePreviewUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for fontProcessorUpdate
     *
     * Updates font file and metadata in storage.
     *
     */
    public function testFontProcessorUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
