<?php
/**
 * ImageProcessorApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetProcessor\Test\Api;

use \Aurigma\AssetProcessor\Configuration;
use \Aurigma\AssetProcessor\ApiException;
use \Aurigma\AssetProcessor\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ImageProcessorApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ImageProcessorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for imageProcessorImportImage
     *
     * Imports image from source file and saves it to storage..
     *
     */
    public function testImageProcessorImportImage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for imageProcessorPreparePreview
     *
     * Creates preview image for image taken from storage..
     *
     */
    public function testImageProcessorPreparePreview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for imageProcessorPreparePreviewUrl
     *
     * Creates preview image for image taken from storage..
     *
     */
    public function testImageProcessorPreparePreviewUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for imageProcessorUpdate
     *
     * Updates image file and metadata in storage.
     *
     */
    public function testImageProcessorUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
