<?php
/**
 * MockupProcessorApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Asset Processor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetProcessor\Test\Api;

use \Aurigma\AssetProcessor\Configuration;
use \Aurigma\AssetProcessor\ApiException;
use \Aurigma\AssetProcessor\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MockupProcessorApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MockupProcessorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for mockupProcessorImportMockup
     *
     * Imports a mockup from the source file and saves it to the storage..
     *
     */
    public function testMockupProcessorImportMockup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mockupProcessorPreparePreview
     *
     * Creates a preview for the mockup taken from the storage..
     *
     */
    public function testMockupProcessorPreparePreview()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mockupProcessorPreparePreviewUrl
     *
     * Creates a preview for the mockup taken from the storage..
     *
     */
    public function testMockupProcessorPreparePreviewUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mockupProcessorUpdate
     *
     * Updates the mockup file and metadata in the storage..
     *
     */
    public function testMockupProcessorUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
