<?php
/**
 * PrivateDesignProcessorApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AssetProcessor API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Aurigma\AssetProcessor\Test\Api;

use \Aurigma\AssetProcessor\Configuration;
use \Aurigma\AssetProcessor\ApiException;
use \Aurigma\AssetProcessor\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PrivateDesignProcessorApiTest Class Doc Comment
 *
 * @category Class
 * @package  Aurigma\AssetProcessor
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PrivateDesignProcessorApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for privateDesignProcessorCheck
     *
     * Checks if design taken from private storage has any problems.
     *
     */
    public function testPrivateDesignProcessorCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorCreateBlankDesign
     *
     * Creates design by product model and saves it to private storage.
     *
     */
    public function testPrivateDesignProcessorCreateBlankDesign()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorEmbedDataSchema
     *
     * Embeds linked data schema to the design file.
     *
     */
    public function testPrivateDesignProcessorEmbedDataSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorExportDesign
     *
     * Exports design file.
     *
     */
    public function testPrivateDesignProcessorExportDesign()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorExtractDataSchema
     *
     * Extracts data schema from design file and saves it to the specified folder.
     *
     */
    public function testPrivateDesignProcessorExtractDataSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorGetDepositPhotos
     *
     * Return information about inserted images from DepositPhotos.
     *
     */
    public function testPrivateDesignProcessorGetDepositPhotos()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorImportDesign
     *
     * Imports design from source file and saves it to private storage..
     *
     */
    public function testPrivateDesignProcessorImportDesign()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorLinkDataSchema
     *
     * Links data schema to the design file.
     *
     */
    public function testPrivateDesignProcessorLinkDataSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorPreparePreview
     *
     * Creates preview image for design taken from private storage..
     *
     */
    public function testPrivateDesignProcessorPreparePreview()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorPreparePreviewUrl
     *
     * Creates preview image for design taken from private storage..
     *
     */
    public function testPrivateDesignProcessorPreparePreviewUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorRemoveDataSchema
     *
     * Removes data schema from the design file.
     *
     */
    public function testPrivateDesignProcessorRemoveDataSchema()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for privateDesignProcessorUpdate
     *
     * Updates design file and metadata in private storage.
     *
     */
    public function testPrivateDesignProcessorUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
